v1 = int(input('Digite um número inteiro: '))
print('A tabuada do número {} eh: \n'.format(v1))
print('{} X 0 = {}'.format(v1, v1*0))
print('{} X 1 = {}'.format(v1, v1*1))
print('{} X 2 = {}'.format(v1, v1*2))
print('{} X 3 = {}'.format(v1, v1*3))
print('{} X 4 = {}'.format(v1, v1*4))
print('{} X 5 = {}'.format(v1, v1*5))
print('{} X 6 = {}'.format(v1, v1*6))
print('{} X 7 = {}'.format(v1, v1*7))
print('{} X 8 = {}'.format(v1, v1*8))
print('{} X 9 = {}'.format(v1, v1*9))
print('{} X 10 = {}'.format(v1, v1*10))